=== chatelao/xDuinoRails_Thot/firmware/definitions/signals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="signalDefinitions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="signal" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="lightbulbs">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="lightbulb" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="x" type="xs:decimal" use="required"/>
                        <xs:attribute name="y" type="xs:decimal" use="required"/>
                        <xs:attribute name="color" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="aspects">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="aspect" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="light" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="country" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="svg" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chatelao/xDuinoRails_Thot/firmware/definitions/nl-Dwergsein.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="nl" name="NL-Dwergsein" svg="NL-Dwergsein.svg" outline="M -200,250 L 200,250 L 200,-200 L -200,-200 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L_Green" x="0" y="100" color="green" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_Red" x="-100" y="-80" color="red" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_Yellow" x="100" y="-80" color="yellow" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Groen" short="Groen" long="Groen">
        <light id="L_Green" />
      </aspect>
      <aspect name="Groen knipper" short="GroenK" long="Groen knipper">
        <light id="L_Green" blink="true" />
      </aspect>
      <aspect name="Geel" short="Geel" long="Geel">
        <light id="L_Yellow" />
      </aspect>
      <aspect name="Geel knipper" short="GeelK" long="Geel knipper">
        <light id="L_Yellow" blink="true" />
      </aspect>
      <aspect name="Rood" short="Rood" long="Rood">
        <light id="L_Red" />
      </aspect>
      <aspect name="Rood knipper" short="RoodK" long="Rood knipper">
        <light id="L_Red" blink="true" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/firmware/definitions/nl.xml
<?xml version="1.0" encoding="UTF-8"?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="nl" name="NL-Hoofdsein" svg="NL-Hoofdsein.svg" outline="M -250,600 L 250,600 L 250,-1200 L -250,-1200 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L_Green" x="0" y="400" color="green" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>
      <lightbulb id="L_Yellow" x="0" y="0" color="yellow" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>
      <lightbulb id="L_Red" x="0" y="-400" color="red" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>

      <!-- Matrix numbers (approx y=-800) -->
      <!-- 13: "1" centered at x=-70, "3" centered at x=70 -->
      <!-- Digit 1: Block from x=-80 to -60, y=-80 to 80 -->
      <!-- Digit 3: Blocky 3 -->
      <lightbulb id="M_13" x="0" y="-800" color="yellow" d="M -80,-80 L -80,80 L -60,80 L -60,-80 Z M 40,80 L 100,80 L 100,60 L 60,60 L 60,10 L 90,10 L 90,-10 L 60,-10 L 60,-60 L 100,-60 L 100,-80 L 40,-80 L 40,-60 L 80,-60 L 80,-10 L 60,-10 L 60,10 L 80,10 L 80,60 L 40,60 Z"/>

      <!-- 8 -->
      <lightbulb id="M_8" x="0" y="-800" color="yellow" d="M -50,80 L 50,80 L 50,-80 L -50,-80 Z M -30,60 L -30,10 L 30,10 L 30,60 Z M -30,-10 L -30,-60 L 30,-60 L 30,-10 Z"/>

      <!-- 6 -->
      <lightbulb id="M_6" x="0" y="-800" color="yellow" d="M -50,80 L 50,80 L 50,60 L -30,60 L -30,10 L 50,10 L 50,-80 L -50,-80 Z M -30,-10 L -30,-60 L 30,-60 L 30,-10 Z"/>

    </lightbulbs>
    <aspects>
      <aspect name="Groen" short="Groen" long="Groen">
        <light id="L_Green"/>
      </aspect>
      <aspect name="Groen + 13" short="Groen13" long="Groen met 130 km/h">
        <light id="L_Green"/>
        <light id="M_13"/>
      </aspect>
      <aspect name="Groen knipper" short="GroenK" long="Groen knipper">
        <light id="L_Green" blink="true"/>
      </aspect>
      <aspect name="Geel + 8 knipper" short="Geel8K" long="Geel met 80 km/h knipper">
        <light id="L_Yellow"/>
        <light id="M_8" blink="true"/>
      </aspect>
       <aspect name="Geel + 6" short="Geel6" long="Geel met 60 km/h">
        <light id="L_Yellow"/>
        <light id="M_6"/>
      </aspect>
      <aspect name="Geel" short="Geel" long="Geel">
        <light id="L_Yellow"/>
      </aspect>
      <aspect name="Geel knipper" short="GeelK" long="Geel knipper">
        <light id="L_Yellow" blink="true"/>
      </aspect>
      <aspect name="Rood" short="Rood" long="Rood">
        <light id="L_Red"/>
      </aspect>
      <aspect name="Rood knipper" short="RoodK" long="Rood knipper">
        <light id="L_Red" blink="true"/>
      </aspect>
    </aspects>
  </signal>

  <signal country="nl" name="NL-Dwergsein" svg="NL-Dwergsein.svg" outline="M -200,250 L 200,250 L 200,-200 L -200,-200 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L_Green" x="0" y="100" color="green" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0"/>
      <lightbulb id="L_Red" x="-100" y="-80" color="red" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0"/>
      <lightbulb id="L_Yellow" x="100" y="-80" color="yellow" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0"/>
    </lightbulbs>
    <aspects>
      <aspect name="Groen" short="Groen" long="Groen">
        <light id="L_Green"/>
      </aspect>
      <aspect name="Groen knipper" short="GroenK" long="Groen knipper">
        <light id="L_Green" blink="true"/>
      </aspect>
      <aspect name="Geel" short="Geel" long="Geel">
        <light id="L_Yellow"/>
      </aspect>
      <aspect name="Geel knipper" short="GeelK" long="Geel knipper">
        <light id="L_Yellow" blink="true"/>
      </aspect>
      <aspect name="Rood" short="Rood" long="Rood">
        <light id="L_Red"/>
      </aspect>
      <aspect name="Rood knipper" short="RoodK" long="Rood knipper">
        <light id="L_Red" blink="true"/>
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/ch-N.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="ch" name="CH-N-Hauptsignal-1" svg="CH-N-Hauptsignal-1.svg" outline="M -350,350 L 350,350 L 350,-350 L -350,-350 Z" outlineColor="#000000">
    <decorations>
      <decoration d="M 0,0 m -340,0 a 340,340 0 1,0 680,0 a 340,340 0 1,0 -680,0 M 0,0 m -310,0 a 310,310 0 1,1 620,0 a 310,310 0 1,1 -620,0" color="white" />
    </decorations>
    <lightbulbs>
      <lightbulb id="L1" x="139" y="-80" color="green" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L2" x="-139" y="-80" color="orange" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L3" x="0" y="160" color="red" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Halt" short="Halt" long="Halt">
        <light id="L3" />
      </aspect>
      <aspect name="Freie Fahrt" short="Fb1" long="Fahrbegriff 1">
        <light id="L1" />
      </aspect>
      <aspect name="Warnung" short="Fb2" long="Fahrbegriff 2">
        <light id="L2" />
      </aspect>
      <aspect name="Hilfssignal" short="Hilfssignal" long="Hilfssignal">
        <light id="L3" blink="true" />
      </aspect>
    </aspects>
  </signal>
  <signal country="ch" name="CH-N-Vorsignal-1" svg="CH-N-Vorsignal-1.svg" outline="M -250,250 L 250,250 L 250,-250 L -250,-250 Z" outlineColor="#000000" borderColor="#ffffff" borderWidth="20">
    <lightbulbs>
      <lightbulb id="L1" x="120" y="0" color="green" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L2" x="-120" y="0" color="orange" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Freie Fahrt" short="Fb1*" long="AnkÃ¼ndigung Freie Fahrt">
        <light id="L1" />
      </aspect>
      <aspect name="Warnung" short="Warnung" long="Warnung">
        <light id="L2" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/de-HV.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="de" name="DE-HV-Hauptsignal-1" svg="DE-HV-Hauptsignal-1.svg" outline="M -350,400 L -250,500 L 250,500 L 350,400 L 350,-1100 L -350,-1100 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="230" color="green" d="m -70, 0 a 70,70 0 1,0 140,0 a 70,70 0 1,0 -140,0" />
      <lightbulb id="L2_Left" x="-120" y="0" color="red" d="m -70, 0 a 70,70 0 1,0 140,0 a 70,70 0 1,0 -140,0" />
      <lightbulb id="L2_Right" x="120" y="0" color="red" d="m -70, 0 a 70,70 0 1,0 140,0 a 70,70 0 1,0 -140,0" />
      <lightbulb id="L3" x="0" y="-810" color="yellow" d="m -70, 0 a 70,70 0 1,0 140,0 a 70,70 0 1,0 -140,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Hp 0" short="Hp0" long="Halt">
        <light id="L2_Left" />
        <light id="L2_Right" />
      </aspect>
      <aspect name="Hp 1" short="Hp1" long="Fahrt">
        <light id="L1" />
      </aspect>
      <aspect name="Hp 2" short="Hp2" long="Langsamfahrt">
        <light id="L1" />
        <light id="L3" />
      </aspect>
    </aspects>
  </signal>
  <signal country="de" name="DE-HV-Zwergsignal-1" svg="DE-HV-Zwergsignal-1.svg" outline="M -200,200 L 200,200 L 200,-200 L -200,-200 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1_RED" x="-100" y="0" color="red" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L2_RED" x="100" y="0" color="red" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L3_WHITE" x="-100" y="-100" color="white" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L4_WHITE" x="100" y="100" color="white" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Sh 0" short="Sh0" long="Halt / Fahrverbot">
        <light id="L1_RED" />
        <light id="L2_RED" />
      </aspect>
      <aspect name="Sh 1" short="Sh1" long="Fahrverbot aufgehoben">
        <light id="L3_WHITE" />
        <light id="L4_WHITE" />
      </aspect>
    </aspects>
  </signal>
  <signal country="de" name="DE-HV-Vorsignal-1" svg="DE-HV-Vorsignal-1.svg" outline="M -400,-400 L -400,0 L 0,400 L 400,400 L 400,0 L 0,-400 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L_TR_Y" x="27" y="250" color="yellow" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_TR_G" x="240" y="250" color="green" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_BL_Y" x="-27" y="-250" color="yellow" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_BL_G" x="-240" y="-250" color="green" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Vr 0" short="Vr0" long="Halt erwarten">
        <light id="L_BL_Y" />
        <light id="L_TR_Y" />
      </aspect>
      <aspect name="Vr 1" short="Vr1" long="Fahrt erwarten">
        <light id="L_BL_G" />
        <light id="L_TR_G" />
      </aspect>
      <aspect name="Vr 2" short="Vr2" long="Langsamfahrt erwarten">
        <light id="L_BL_Y" />
        <light id="L_TR_G" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/uk-Colour.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="uk" name="UK-Colour-Light-Signal-4-Aspect" svg="UK-Colour-Light-Signal-4-Aspect.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="30" color="yellow" />
      <lightbulb id="L2" x="0" y="20" color="green" />
      <lightbulb id="L3" x="0" y="10" color="yellow" />
      <lightbulb id="L4" x="0" y="0" color="red" />
    </lightbulbs>
    <aspects>
      <aspect name="Clear" short="G" long="Clear">
        <light id="L2" />
      </aspect>
      <aspect name="Preliminary caution" short="YY" long="Preliminary caution">
        <light id="L1" />
        <light id="L3" />
      </aspect>
      <aspect name="Caution" short="Y" long="Caution">
        <light id="L3" />
      </aspect>
      <aspect name="Danger" short="R" long="Danger">
        <light id="L4" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/ch-ZP.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="ch" name="CH-ZP-Signal" svg="CH-ZP-Signal.svg" outline="M -150,150 L 0,150 L 150,0 L 150,-150 L -150,-150 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L_SMS" x="0" y="0" color="orange" d="M -20,-100 L 20,-100 L 20,100 L -20,100 Z" />
      <lightbulb id="L1" x="-80" y="-80" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L2" x="-80" y="80" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L3" x="80" y="-80" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Abfahren" short="Zp9" long="Abfahren">
        <light id="L_SMS" />
      </aspect>
      <aspect name="Bremse" short="Bremse" long="Bremsprobe">
        <light id="L1" />
        <light id="L2" />
        <light id="L3" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/pl-Manewrowa.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="pl" name="PL-Manewrowa" svg="PL-Manewrowa.svg" outline="M -150,300 L 150,300 L 150,-300 L -150,-300 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="150" color="blue" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L2" x="0" y="-150" color="white" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Ms1 Zabroniona" short="Ms1" long="Jazda manewrowa zabroniona">
        <light id="L1" />
      </aspect>
      <aspect name="Ms2 Dozwolona" short="Ms2" long="Jazda manewrowa dozwolona">
        <light id="L2" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/at-Hauptsignal.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="at" name="AT-Hauptsignal-1" svg="AT-Hauptsignal-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="-250" y="500" color="green" />
      <lightbulb id="L2" x="250" y="0" color="red" />
      <lightbulb id="L3" x="250" y="500" color="yellow" />
      <lightbulb id="L4" x="-250" y="0" color="green" />
    </lightbulbs>
    <aspects>
      <aspect name="Halt" short="Halt" long="Halt">
        <light id="L2" />
      </aspect>
      <aspect name="Frei" short="Frei" long="Frei">
        <light id="L1" />
      </aspect>
      <aspect name="Frei mit 60 km/h" short="Frei 60" long="Frei mit 60 km/h">
        <light id="L1" />
        <light id="L4" />
      </aspect>
      <aspect name="Frei mit 40 km/h" short="Frei 40" long="Frei mit 40 km/h">
        <light id="L1" />
        <light id="L3" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>
