=== chatelao/xDuinoRails_Thot/firmware/definitions/signals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="signalDefinitions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="signal" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="lightbulbs">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="lightbulb" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="x" type="xs:decimal" use="required"/>
                        <xs:attribute name="y" type="xs:decimal" use="required"/>
                        <xs:attribute name="color" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="aspects">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="aspect" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="light" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="country" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="svg" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chatelao/xDuinoRails_Thot/definitions/us-3.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="us" name="US-3-aspect-vertical" svg="US-3-aspect-vertical.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="500" color="green" />
      <lightbulb id="L2" x="0" y="0" color="yellow" />
      <lightbulb id="L3" x="0" y="-500" color="red" />
    </lightbulbs>
    <aspects>
      <aspect name="Stop" short="Stop" long="Stop">
        <light id="L3" />
      </aspect>
      <aspect name="Clear" short="Clear" long="Clear">
        <light id="L1" />
      </aspect>
      <aspect name="Approach" short="Approach" long="Approach">
        <light id="L2" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/ch-Raeumungssignal.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="ch" name="CH-Raeumungssignal" svg="CH-Raeumungssignal.svg" outline="M -260,260 L 260,260 L 260,-260 L -260,-260 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="-200" y="200" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L3" x="0" y="200" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L5" x="200" y="200" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L7" x="-100" y="100" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L8" x="0" y="100" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L9" x="100" y="100" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L11" x="-200" y="0" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L12" x="-100" y="0" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L13" x="0" y="0" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L14" x="100" y="0" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L15" x="200" y="0" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L17" x="-100" y="-100" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L18" x="0" y="-100" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L19" x="100" y="-100" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L21" x="-200" y="-200" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L23" x="0" y="-200" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L25" x="200" y="-200" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Rangieren verboten" short="Verboten" long="Rangieren verboten">
        <light id="L1" />
        <light id="L7" />
        <light id="L13" />
        <light id="L19" />
        <light id="L25" />
        <light id="L21" />
        <light id="L17" />
        <light id="L9" />
        <light id="L5" />
      </aspect>
      <aspect name="Rangieren gestattet" short="Gestattet" long="Rangieren gestattet">
        <light id="L3" />
        <light id="L8" />
        <light id="L13" />
        <light id="L18" />
        <light id="L23" />
      </aspect>
      <aspect name="Rangieren erlaubt" short="Erlaubt" long="Rangieren erlaubt">
        <light id="L3" />
        <light id="L8" />
        <light id="L13" />
        <light id="L18" />
        <light id="L23" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/de-KS.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="de" name="DE-KS-Signal" svg="DE-KS-Signal.svg" outline="M -350,750 L 350,750 L 350,-750 L -350,-750 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="500" color="green" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L2" x="0" y="0" color="red" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L3" x="0" y="-500" color="yellow" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L4" x="-80" y="-330" color="white" d="m -60, 0 a 60,60 0 1,0 120,0 a 60,60 0 1,0 -120,0" />
      <lightbulb id="L5" x="80" y="-170" color="white" d="m -60, 0 a 60,60 0 1,0 120,0 a 60,60 0 1,0 -120,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Hp 0" short="Hp0" long="Halt">
        <light id="L2" />
      </aspect>
      <aspect name="Ks 1" short="Ks1" long="Fahrt / Fahrt erwarten">
        <light id="L1" />
      </aspect>
      <aspect name="Ks 2" short="Ks2" long="Halt erwarten">
        <light id="L3" />
      </aspect>
      <aspect name="Sh 1" short="Sh1" long="Fahrverbot aufgehoben">
        <light id="L4" />
        <light id="L5" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/firmware/definitions/fr-Carre.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="fr" name="FR-Carre-Violet-1" svg="FR-Carre-Violet-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="0" color="violet" />
      <lightbulb id="L2" x="0" y="-50" color="white" />
    </lightbulbs>
    <aspects>
      <aspect name="Carré violet" short="Cv" long="Carré violet">
        <light id="L1" />
      </aspect>
      <aspect name="Manoeuvre" short="M" long="Manoeuvre">
        <light id="L2" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/ch-Zwergsignal.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="ch" name="CH-Zwergsignal" svg="CH-Zwergsignal.svg" outline="M -150,150 L 0,150 L 150,0 L 150,-150 L -150,-150 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="-80" y="-80" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L2" x="-80" y="80" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L3" x="80" y="-80" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Halt" short="Halt" long="Halt">
        <light id="L1" />
        <light id="L3" />
      </aspect>
      <aspect name="Fahrt" short="Fahrt" long="Fahrt">
        <light id="L1" />
        <light id="L2" />
      </aspect>
      <aspect name="Fahrt mit Vorsicht" short="FahrtV" long="Fahrt mit Vorsicht">
        <light id="L2" />
        <light id="L3" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/de-ZS.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="de" name="DE-ZS-Signal" svg="DE-ZS-Signal.svg" outline="M -200,200 L 200,200 L 200,-200 L -200,-200 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L_Zs1_Top" x="0" y="100" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L_Zs1_BL" x="-80" y="-80" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L_Zs1_BR" x="80" y="-80" color="white" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L_Zs7_TL" x="-80" y="80" color="yellow" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L_Zs7_TR" x="80" y="80" color="yellow" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
      <lightbulb id="L_Zs7_Bot" x="0" y="-100" color="yellow" d="m -40, 0 a 40,40 0 1,0 80,0 a 40,40 0 1,0 -80,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Zs 1" short="Zs1" long="Ersatzsignal">
        <light id="L_Zs1_Top" />
        <light id="L_Zs1_BL" />
        <light id="L_Zs1_BR" />
      </aspect>
      <aspect name="Zs 7" short="Zs7" long="Gegengleisfahrt-Ersatzsignal">
        <light id="L_Zs7_TL" />
        <light id="L_Zs7_TR" />
        <light id="L_Zs7_Bot" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/at.xml
<?xml version="1.0" encoding="UTF-8"?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="at" name="AT-Hauptsignal-1" svg="AT-Hauptsignal-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="-250" y="500" color="green"/>
      <lightbulb id="L2" x="250" y="0" color="red"/>
      <lightbulb id="L3" x="250" y="500" color="yellow"/>
      <lightbulb id="L4" x="-250" y="0" color="green"/>
    </lightbulbs>
    <aspects>
      <aspect name="Halt" short="Halt" long="Halt">
        <light id="L2"/>
      </aspect>
      <aspect name="Frei" short="Frei" long="Frei">
        <light id="L1"/>
      </aspect>
      <aspect name="Frei mit 60 km/h" short="Frei 60" long="Frei mit 60 km/h">
        <light id="L1"/>
        <light id="L4"/>
      </aspect>
      <aspect name="Frei mit 40 km/h" short="Frei 40" long="Frei mit 40 km/h">
        <light id="L1"/>
        <light id="L3"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="at" name="AT-Zwergsignal-1" svg="AT-Zwergsignal-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="100" color="white"/>
      <lightbulb id="L2" x="0" y="-100" color="white"/>
      <lightbulb id="L3" x="-100" y="0" color="white"/>
      <lightbulb id="L4" x="100" y="0" color="white"/>
    </lightbulbs>
    <aspects>
      <aspect name="Halt" short="Halt" long="Halt">
        <light id="L3"/>
        <light id="L4"/>
      </aspect>
      <aspect name="Fahrt" short="Fahrt" long="Fahrt">
        <light id="L1"/>
        <light id="L2"/>
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/uk-Ground.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="uk" name="UK-Ground-Position-Light" svg="UK-Ground-Position-Light.svg">
    <lightbulbs>
      <lightbulb id="L1" x="-50" y="0" color="red" />
      <lightbulb id="L2" x="50" y="0" color="red" />
      <lightbulb id="L3" x="-50" y="0" color="white" />
      <lightbulb id="L4" x="50" y="100" color="white" />
    </lightbulbs>
    <aspects>
      <aspect name="Danger" short="Stop" long="Danger">
        <light id="L1" />
        <light id="L2" />
      </aspect>
      <aspect name="Proceed" short="Go" long="Proceed">
        <light id="L3" />
        <light id="L4" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>
