=== chatelao/xDuinoRails_Thot/firmware/definitions/signals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="signalDefinitions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="signal" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="lightbulbs">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="lightbulb" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="x" type="xs:decimal" use="required"/>
                        <xs:attribute name="y" type="xs:decimal" use="required"/>
                        <xs:attribute name="color" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="aspects">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="aspect" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="light" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="country" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="svg" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== chatelao/xDuinoRails_Thot/definitions/de-SV.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="de" name="DE-SV-Signal" svg="DE-SV-Signal.svg" outline="M -250,150 L 250,150 L 250,-150 L -250,-150 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L_Left_R" x="-150" y="0" color="red" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_Left_G" x="-150" y="0" color="green" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_Left_Y" x="-150" y="0" color="yellow" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_Right_R" x="150" y="0" color="red" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_Right_G" x="150" y="0" color="green" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
      <lightbulb id="L_Right_Y" x="150" y="0" color="yellow" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0" />
    </lightbulbs>
    <aspects>
      <aspect name="Sv 0" short="Sv0" long="Halt">
        <light id="L_Left_R" />
        <light id="L_Right_R" />
      </aspect>
      <aspect name="Sv 1" short="Sv1" long="Fahrt">
        <light id="L_Left_G" />
        <light id="L_Right_G" />
      </aspect>
      <aspect name="Sv 2" short="Sv2" long="Fahrt, Halt erwarten">
        <light id="L_Left_G" />
        <light id="L_Right_Y" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/fr-Signalisation.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="fr" name="FR-Signalisation-Lumineuse-1" svg="FR-Signalisation-Lumineuse-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="10" color="green" />
      <lightbulb id="L2" x="0" y="0" color="yellow" />
      <lightbulb id="L3" x="0" y="-10" color="red" />
      <lightbulb id="L4" x="0" y="-20" color="red" />
    </lightbulbs>
    <aspects>
      <aspect name="Carré" short="C" long="Carré">
        <light id="L3" />
        <light id="L4" />
      </aspect>
      <aspect name="Sémaphore" short="S" long="Sémaphore">
        <light id="L3" />
      </aspect>
      <aspect name="Avertissement" short="A" long="Avertissement">
        <light id="L2" />
      </aspect>
      <aspect name="Voie libre" short="VL" long="Voie libre">
        <light id="L1" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/firmware/definitions/uk.xml
<?xml version="1.0" encoding="UTF-8"?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="uk" name="UK-Colour-Light-Signal-2-Aspect" svg="UK-Colour-Light-Signal-2-Aspect.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="500" color="green"/>
      <lightbulb id="L2" x="0" y="0" color="red"/>
    </lightbulbs>
    <aspects>
      <aspect name="Clear">
        <light id="L1"/>
      </aspect>
      <aspect name="Danger">
        <light id="L2"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="uk" name="UK-Colour-Light-Signal-3-Aspect" svg="UK-Colour-Light-Signal-3-Aspect.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="500" color="green"/>
      <lightbulb id="L2" x="0" y="0" color="yellow"/>
      <lightbulb id="L3" x="0" y="-500" color="red"/>
    </lightbulbs>
    <aspects>
      <aspect name="Clear">
        <light id="L1"/>
      </aspect>
      <aspect name="Caution">
        <light id="L2"/>
      </aspect>
      <aspect name="Danger">
        <light id="L3"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="uk" name="UK-Colour-Light-Signal-4-Aspect" svg="UK-Colour-Light-Signal-4-Aspect.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="30" color="yellow"/>
      <lightbulb id="L2" x="0" y="20" color="green"/>
      <lightbulb id="L3" x="0" y="10" color="yellow"/>
      <lightbulb id="L4" x="0" y="0" color="red"/>
    </lightbulbs>
    <aspects>
      <aspect name="Clear">
        <light id="L2"/>
      </aspect>
      <aspect name="Preliminary caution">
        <light id="L1"/>
        <light id="L3"/>
      </aspect>
      <aspect name="Caution">
        <light id="L3"/>
      </aspect>
      <aspect name="Danger">
        <light id="L4"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="uk" name="UK-Lower-Quadrant-Stop-Semaphore" svg="UK-Lower-Quadrant-Stop-Semaphore.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="0" color="green"/>
      <lightbulb id="L2" x="0" y="0" color="red"/>
    </lightbulbs>
    <aspects>
      <aspect name="Clear">
        <light id="L1"/>
      </aspect>
      <aspect name="Danger">
        <light id="L2"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="uk" name="UK-Lower-Quadrant-Distant-Semaphore" svg="UK-Lower-Quadrant-Distant-Semaphore.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="0" color="green"/>
      <lightbulb id="L2" x="0" y="0" color="yellow"/>
    </lightbulbs>
    <aspects>
      <aspect name="Clear">
        <light id="L1"/>
      </aspect>
      <aspect name="Caution">
        <light id="L2"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="uk" name="UK-Position-Light-Signal" svg="UK-Position-Light-Signal.svg">
    <lightbulbs>
      <lightbulb id="L1" x="-100" y="100" color="white"/>
      <lightbulb id="L2" x="100" y="-100" color="white"/>
      <lightbulb id="L3" x="-100" y="-100" color="red"/>
      <lightbulb id="L4" x="100" y="100" color="red"/>
    </lightbulbs>
    <aspects>
      <aspect name="Proceed">
        <light id="L1"/>
        <light id="L2"/>
      </aspect>
      <aspect name="Stop">
        <light id="L3"/>
        <light id="L4"/>
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/firmware/definitions/pl.xml
<?xml version="1.0" encoding="UTF-8"?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <!-- Polish Signals -->

  <!-- 5-Chamber Main Signal -->
  <signal country="pl" name="PL-Hauptsignal-5L" svg="PL-Hauptsignal-5L.svg" outline="M -200,600 L 200,600 L 200,-600 L -200,-600 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="400" color="green" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>
      <lightbulb id="L2" x="0" y="200" color="orange" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>
      <lightbulb id="L3" x="0" y="0" color="red" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>
      <lightbulb id="L4" x="0" y="-200" color="orange" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>
      <lightbulb id="L5" x="0" y="-400" color="white" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>
    </lightbulbs>
    <aspects>
      <aspect name="S1 Stój" short="S1" long="Stój">
        <light id="L3"/>
      </aspect>
      <aspect name="S2 Vmax" short="S2" long="Jazda z największą dozwoloną prędkością">
        <light id="L1"/>
      </aspect>
      <aspect name="S3 Vmax (n. 100)" short="S3" long="Jazda Vmax, następnie 100 km/h">
        <light id="L1"/>
      </aspect>
      <aspect name="S4 Vmax (n. 40/60)" short="S4" long="Jazda Vmax, następnie 40/60 km/h">
        <light id="L2"/>
      </aspect>
      <aspect name="S5 Vmax (n. Stój)" short="S5" long="Jazda Vmax, następnie Stój">
        <light id="L2"/>
      </aspect>
      <aspect name="S10 40 (n. Vmax)" short="S10" long="Jazda 40 km/h, następnie Vmax">
        <light id="L1"/>
        <light id="L4"/>
      </aspect>
      <aspect name="S11 40 (n. 100)" short="S11" long="Jazda 40 km/h, następnie 100 km/h">
        <light id="L1"/>
        <light id="L4"/>
      </aspect>
      <aspect name="S12 40 (n. 40/60)" short="S12" long="Jazda 40 km/h, następnie 40/60 km/h">
        <light id="L2"/>
        <light id="L4"/>
      </aspect>
      <aspect name="S13 40 (n. Stój)" short="S13" long="Jazda 40 km/h, następnie Stój">
        <light id="L2"/>
        <light id="L4"/>
      </aspect>
      <aspect name="Sz Sygnał Zastępczy" short="Sz" long="Sygnał Zastępczy">
        <light id="L3"/>
        <light id="L5"/>
      </aspect>
    </aspects>
  </signal>

  <!-- Shunting Signal (Tarcza Manewrowa) -->
  <signal country="pl" name="PL-Manewrowa" svg="PL-Manewrowa.svg" outline="M -150,300 L 150,300 L 150,-300 L -150,-300 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="150" color="blue" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0"/>
      <lightbulb id="L2" x="0" y="-150" color="white" d="m -80, 0 a 80,80 0 1,0 160,0 a 80,80 0 1,0 -160,0"/>
    </lightbulbs>
    <aspects>
      <aspect name="Ms1 Zabroniona" short="Ms1" long="Jazda manewrowa zabroniona">
        <light id="L1"/>
      </aspect>
      <aspect name="Ms2 Dozwolona" short="Ms2" long="Jazda manewrowa dozwolona">
        <light id="L2"/>
      </aspect>
    </aspects>
  </signal>

  <!-- Distant Signal (Vorsignal) -->
  <signal country="pl" name="PL-Vorsignal" svg="PL-Vorsignal.svg" outline="M -200,300 L 200,300 L 200,-300 L -200,-300 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="150" color="green" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>
      <lightbulb id="L2" x="0" y="-150" color="orange" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0"/>
    </lightbulbs>
    <aspects>
      <aspect name="Os1 n. Stój" short="Os1" long="Następny sygnał Stój">
        <light id="L2"/>
      </aspect>
      <aspect name="Os2 n. Vmax" short="Os2" long="Następny sygnał Vmax">
        <light id="L1"/>
      </aspect>
      <aspect name="Os3 n. 100" short="Os3" long="Następny sygnał 100 km/h">
        <light id="L1"/>
      </aspect>
      <aspect name="Os4 n. 40/60" short="Os4" long="Następny sygnał 40/60 km/h">
        <light id="L2"/>
      </aspect>
    </aspects>
  </signal>

</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/pl-Hauptsignal.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="pl" name="PL-Hauptsignal-5L" svg="PL-Hauptsignal-5L.svg" outline="M -200,600 L 200,600 L 200,-600 L -200,-600 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="400" color="green" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L2" x="0" y="200" color="orange" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L3" x="0" y="0" color="red" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L4" x="0" y="-200" color="orange" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L5" x="0" y="-400" color="white" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
    </lightbulbs>
    <aspects>
      <aspect name="S1 Stój" short="S1" long="Stój">
        <light id="L3" />
      </aspect>
      <aspect name="S2 Vmax" short="S2" long="Jazda z największą dozwoloną prędkością">
        <light id="L1" />
      </aspect>
      <aspect name="S3 Vmax (n. 100)" short="S3" long="Jazda Vmax, następnie 100 km/h">
        <light id="L1" />
      </aspect>
      <aspect name="S4 Vmax (n. 40/60)" short="S4" long="Jazda Vmax, następnie 40/60 km/h">
        <light id="L2" />
      </aspect>
      <aspect name="S5 Vmax (n. Stój)" short="S5" long="Jazda Vmax, następnie Stój">
        <light id="L2" />
      </aspect>
      <aspect name="S10 40 (n. Vmax)" short="S10" long="Jazda 40 km/h, następnie Vmax">
        <light id="L1" />
        <light id="L4" />
      </aspect>
      <aspect name="S11 40 (n. 100)" short="S11" long="Jazda 40 km/h, następnie 100 km/h">
        <light id="L1" />
        <light id="L4" />
      </aspect>
      <aspect name="S12 40 (n. 40/60)" short="S12" long="Jazda 40 km/h, następnie 40/60 km/h">
        <light id="L2" />
        <light id="L4" />
      </aspect>
      <aspect name="S13 40 (n. Stój)" short="S13" long="Jazda 40 km/h, następnie Stój">
        <light id="L2" />
        <light id="L4" />
      </aspect>
      <aspect name="Sz Sygnał Zastępczy" short="Sz" long="Sygnał Zastępczy">
        <light id="L3" />
        <light id="L5" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/firmware/definitions/ch.xml
<?xml version="1.0" encoding="UTF-8"?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="ch" name="CH-N-Hauptsignal-1" svg="CH-N-Hauptsignal-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="500" color="green"/>
      <lightbulb id="L2" x="-250" y="0" color="yellow"/>
      <lightbulb id="L3" x="250" y="0" color="red"/>
      <lightbulb id="L4" x="0" y="-500" color="white"/>
    </lightbulbs>
    <aspects>
      <aspect name="Halt">
        <light id="L3"/>
      </aspect>
      <aspect name="Freie Fahrt">
        <light id="L1"/>
      </aspect>
      <aspect name="Warnung">
        <light id="L2"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="ch" name="CH-L-Hauptsignal-1" svg="CH-L-Hauptsignal-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="500" color="green"/>
      <lightbulb id="L2" x="0" y="0" color="red"/>
      <lightbulb id="L3" x="0" y="-500" color="yellow"/>
    </lightbulbs>
    <aspects>
      <aspect name="Halt">
        <light id="L2"/>
      </aspect>
      <aspect name="Freie Fahrt">
        <light id="L1"/>
      </aspect>
      <aspect name="Warnung">
        <light id="L3"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="ch" name="CH-L-Vorsignal-1" svg="CH-L-Vorsignal-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="-250" y="250" color="green"/>
      <lightbulb id="L2" x="250" y="250" color="yellow"/>
      <lightbulb id="L3" x="-250" y="-250" color="green"/>
      <lightbulb id="L4" x="250" y="-250" color="yellow"/>
    </lightbulbs>
    <aspects>
      <aspect name="Warnung">
        <light id="L2"/>
        <light id="L4"/>
      </aspect>
      <aspect name="Freie Fahrt">
        <light id="L1"/>
        <light id="L3"/>
      </aspect>
      <aspect name="Geschwindigkeits-AnkÃ¼ndigung 40 km/h">
        <light id="L1"/>
        <light id="L4"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="ch" name="CH-N-Vorsignal-1" svg="CH-N-Vorsignal-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="500" color="green"/>
      <lightbulb id="L2" x="-250" y="0" color="yellow"/>
    </lightbulbs>
    <aspects>
      <aspect name="Freie Fahrt">
        <light id="L1"/>
      </aspect>
      <aspect name="Warnung">
        <light id="L2"/>
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/definitions/de-HL.xml
<?xml version='1.0' encoding='utf-8'?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="de" name="DE-HL-Signal" svg="DE-HL-Signal.svg" outline="M -350,1000 L 350,1000 L 350,-1000 L -350,-1000 Z" outlineColor="#000000">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="750" color="yellow" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L2" x="0" y="250" color="green" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L3" x="0" y="-250" color="red" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L4" x="0" y="-750" color="yellow" d="m -100, 0 a 100,100 0 1,0 200,0 a 100,100 0 1,0 -200,0" />
      <lightbulb id="L5" x="0" y="-900" color="green" d="M -150,-30 L 150,-30 L 150,30 L -150,30 Z" />
      <lightbulb id="L6" x="0" y="-900" color="yellow" d="M -150,-30 L 150,-30 L 150,30 L -150,30 Z" />
    </lightbulbs>
    <aspects>
      <aspect name="Hl 13" short="Hl13" long="Halt">
        <light id="L3" />
      </aspect>
      <aspect name="Hl 1" short="Hl1" long="Fahrt">
        <light id="L2" />
      </aspect>
      <aspect name="Hl 10" short="Hl10" long="Halt erwarten">
        <light id="L1" />
      </aspect>
      <aspect name="Hl 9a" short="Hl9a" long="Fahrt 40 km/h">
        <light id="L1" />
      </aspect>
      <aspect name="Hl 9b" short="Hl9b" long="Fahrt 60 km/h">
        <light id="L1" />
        <light id="L6" />
      </aspect>
      <aspect name="Hl 12a" short="Hl12a" long="Fahrt 40 km/h, Halt erwarten">
        <light id="L1" />
        <light id="L4" />
      </aspect>
      <aspect name="Hl 12b" short="Hl12b" long="Fahrt 60 km/h, Halt erwarten">
        <light id="L1" />
        <light id="L6" />
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>

=== chatelao/xDuinoRails_Thot/firmware/definitions/it.xml
<?xml version="1.0" encoding="UTF-8"?>
<signalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="signals.xsd">
  <signal country="it" name="IT-Segnale-Luminoso-1" svg="IT-Segnale-Luminoso-1.svg">
    <lightbulbs>
      <lightbulb id="L1" x="0" y="10" color="green"/>
      <lightbulb id="L2" x="0" y="0" color="red"/>
      <lightbulb id="L3" x="0" y="-10" color="yellow"/>
    </lightbulbs>
    <aspects>
      <aspect name="Stop" short="R" long="Via impedita">
        <light id="L2"/>
      </aspect>
      <aspect name="Proceed" short="V" long="Via libera">
        <light id="L1"/>
      </aspect>
      <aspect name="Proceed at reduced speed" short="G" long="Via libera con avviso di ridotta velocitÃ ">
        <light id="L1"/>
        <light id="L3"/>
      </aspect>
    </aspects>
  </signal>
  <signal country="it" name="IT-Marmotta" svg="IT-Marmotta.svg">
    <lightbulbs>
      <lightbulb id="L1" x="-50" y="0" color="white"/> <!-- Left -->
      <lightbulb id="L2" x="50" y="0" color="white"/>  <!-- Right -->
      <lightbulb id="L3" x="0" y="50" color="white"/>  <!-- Top -->
      <lightbulb id="L4" x="0" y="-50" color="white"/> <!-- Bottom -->
    </lightbulbs>
    <aspects>
      <aspect name="Stop" short="Stop" long="Via impedita"> <!-- Via impedita -->
        <light id="L1"/>
        <light id="L2"/>
      </aspect>
      <aspect name="Proceed" short="Via" long="Via libera"> <!-- Via libera -->
        <light id="L3"/>
        <light id="L4"/>
      </aspect>
    </aspects>
  </signal>
</signalDefinitions>
